name: ci
run-name: ci - ${{github.event.pull_request.title || github.event.head_commit.message || github.head_ref || github.ref}}

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  workflow_call:

jobs:
  ci:
    runs-on:
      - runs-on
      - run-id=${{ github.run_id }}
      - runner=sm
      - env=production-eu
      - tag=ci
    env:
      BUILD_DIR: 'build'
      CHART_NAME: 'chip'
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set version for branch builds
        if: github.ref_type != 'tag'
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo '0.1.0')
          LAST_TAG=${LAST_TAG#v}
          echo "VERSION=${LAST_TAG}-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set version for tag builds
        if: github.ref_type == 'tag'
        run: |
          VERSION=${{ github.ref_name }}
          VERSION=${VERSION#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.0'

      - name: Install dependencies
        run: go mod download

      - name: Compile
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Build
        if: github.ref_type == 'tag'
        run: |
          GOFIPS140=v1.0.0 GOOS=linux GOARCH=amd64 go build -ldflags="-X 'github.com/collibra/chip/pkg/chip.Version=${{ env.VERSION }}'" -o ${{ env.BUILD_DIR }}/chip-linux-amd64 ./cmd/chip
          GOFIPS140=v1.0.0 GOOS=linux GOARCH=arm64 go build -ldflags="-X 'github.com/collibra/chip/pkg/chip.Version=${{ env.VERSION }}'" -o ${{ env.BUILD_DIR }}chip-linux-arm64 ./cmd/chip
          GOFIPS140=v1.0.0 GOOS=darwin GOARCH=amd64 go build -ldflags="-X 'github.com/collibra/chip/pkg/chip.Version=${{ env.VERSION }}'" -o ${{ env.BUILD_DIR }}/chip-mac-amd64 ./cmd/chip
          GOFIPS140=v1.0.0 GOOS=darwin GOARCH=arm64 go build -ldflags="-X 'github.com/collibra/chip/pkg/chip.Version=${{ env.VERSION }}'" -o ${{ env.BUILD_DIR }}/chip-mac-arm64 ./cmd/chip
          GOFIPS140=v1.0.0 GOOS=windows GOARCH=amd64 go build -ldflags="-X 'github.com/collibra/chip/pkg/chip.Version=${{ env.VERSION }}'" -o ${{ env.BUILD_DIR }}/chip-windows-amd64.exe ./cmd/chip
          GOFIPS140=v1.0.0 GOOS=windows GOARCH=arm64 go build -ldflags="-X 'github.com/collibra/chip/pkg/chip.Version=${{ env.VERSION }}'" -o ${{ env.BUILD_DIR }}/chip-windows-arm64.exe ./cmd/chip

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            ${{ env.BUILD_DIR }}/chip-linux-amd64
            ${{ env.BUILD_DIR }}/chip-linux-arm64
            ${{ env.BUILD_DIR }}/chip-mac-amd64
            ${{ env.BUILD_DIR }}/chip-mac-arm64
            ${{ env.BUILD_DIR }}/chip-windows-amd64.exe
            ${{ env.BUILD_DIR }}/chip-windows-arm64.exe
          release_name: ${{ github.ref }}
          generate_release_notes: true
          make_latest: true
          draft: false
          prerelease: false
